# Site settings
title: Abu&nbsp;Dhabi
client:
  name: Ihre außergewöhnliche Geschichte
  link: "https://visitabudhabi.ae/de-de/default.aspx"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=abudhabi_DE_2019"
description: >
  An was denken Sie beim Namen Barbados? Karibisches Meer, Sonne, Rhythmen und Rum fallen einem sofort ein. Doch die Insel hat noch vieles mehr zu bieten und ist mit über 92 km unberührter, idyllischer Küste ein erstklassiges Traumziel.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/abu-dhabi-2019" # the subpath of your site, e.g. /blog/
img:     "/de/abu-dhabi-2019/_assets/img"
css:     "/de/abu-dhabi-2019/_assets/css"
js:      "/de/abu-dhabi-2019/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
