# Site settings
title: Abu&nbsp;Dhabi
client:
  name: Ihre außergewöhnliche Geschichte
  link: "https://visitabudhabi.ae/de-de/default.aspx"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=abudhabi_DE_2019"
description: >
  Eine moderne Oase am Arabischen Golf, eingerahmt von tropischen Mangroven­landschaften, mäjestätischen Wüsten und traumhaften Strandparadiesen.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/abu-dhabi-2019" # the subpath of your site, e.g. /blog/
img:     "/de/abu-dhabi-2019/_assets/img"
css:     "/de/abu-dhabi-2019/_assets/css"
js:      "/de/abu-dhabi-2019/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
